# Generated by Django 4.1.2 on 2022-10-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0002_publicuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
