# Generated by Django 4.1.2 on 2022-10-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0003_municipality_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='email',
        ),
    ]
