# Generated by Django 4.1.2 on 2022-10-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0005_cabinetposition_remove_publicsector_head_minister_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicsector',
            name='head_minister',
        ),
        migrations.AddField(
            model_name='publicsector',
            name='head_minister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operations.cabinetmember'),
        ),
    ]
