# Generated by Django 4.1.2 on 2022-10-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0007_alter_cabinetmember_office_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='government',
            old_name='Municipality',
            new_name='municipality',
        ),
    ]
