# Generated by Django 4.1.2 on 2022-10-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0008_rename_municipality_government_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='government',
            name='municipality',
        ),
        migrations.CreateModel(
            name='Promissed_Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=1000)),
                ('sector', models.ForeignKey(max_length=225, on_delete=django.db.models.deletion.CASCADE, to='Operations.publicsector')),
            ],
        ),
        migrations.AddField(
            model_name='government',
            name='promissed_duties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operations.promissed_duty'),
        ),
    ]
