# Generated by Django 4.1.2 on 2022-10-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0009_remove_government_municipality_promissed_duty_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promissed_Duty',
            new_name='PromissedDuty',
        ),
        migrations.RenameField(
            model_name='government',
            old_name='year_budget',
            new_name='total_budget',
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=225)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('public_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operations.publicsector')),
            ],
        ),
    ]
