# Generated by Django 4.1.2 on 2022-10-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0011_promissedduty_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='Head_officer',
            new_name='head_officer',
        ),
    ]
