# Generated by Django 4.1.2 on 2022-10-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0013_alter_project_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projest_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Not Complete', 'Not Complete'), ('Half Complete', 'Half Complete')], default='Not Complete', max_length=50),
        ),
    ]
