# Generated by Django 4.1.2 on 2022-10-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0014_project_projest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projest_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Not Complete', 'Not Complete'), ('Half Complete', 'Half Complete')], default='Not Complete', max_length=225),
        ),
        migrations.AlterField(
            model_name='promissedduty',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
