# Generated by Django 4.1.2 on 2022-10-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0015_alter_project_projest_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projest_status',
            new_name='project_status',
        ),
    ]
