# Generated by Django 4.1.2 on 2022-10-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0016_rename_projest_status_project_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=225)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.publicuser')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(blank=True, to='Operations.publiccomment'),
        ),
    ]
